sudo: required
language: bash
services:
  - docker
os:
  - linux
notifications:
  email: false
before_install:
  - sudo docker build -t abarth/divand-rest .
  - docker run --detach --name=divand_rest_container -it -p 8002:8002 abarth/divand_rest
  - docker ps -a
script:
  - sleep 25; ./test/test_bathymetry_curl.sh
  - ./test/test_curl.sh
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "OK" # docker push
